### ISSUE TITLE
(Feature Request)send loot data server http

### ISSUE THREAD

**Issue by nullpointer2017** [kalilistic/Dalamud.Kapture#16]
Are there any plans to implement the function to send information to the server via http, which was available in the ACT version?
I used to use this feature a lot.

**Comment by imgidedin** [comment]
Hi @kalilistic. Could you care to show an example on how to use this? My server doesnt seem to receive anything in the requests:

`{"date":"2023-06-03 11:06:14","get":[],"post":[],"request":[],"headers":{"Host":"fflt.test","Content-Type":"application\/json; charset=utf-8","Content-Length":"835"}}`

**Comment by kalilistic** [comment]
> Hi @kalilistic. Could you care to show an example on how to use this? My server doesnt seem to receive anything in the requests:
> 
> `{"date":"2023-06-03 11:06:14","get":[],"post":[],"request":[],"headers":{"Host":"fflt.test","Content-Type":"application\/json; charset=utf-8","Content-Length":"835"}}`

I haven't looked at this code in a long time so not quite sure off the top of my head. I thought I had some sample code but couldn't find it. I'd start by looking at https://github.com/kalilistic/Kapture/blob/master/src/Kapture/Kapture/Service/LootHTTP.cs to see how the requests are sent.
