### ISSUE TITLE
Does not seem to send anything to Discord through Bridge

### ISSUE THREAD

**Issue by Endracion** [kalilistic/Dalamud.Kapture#28]
Installed and configured discord bridge as required, added ipc and tested other chat types to make sure it worked.
Nothing from kapture shows up however.

**Comment by kalilistic** [comment]
I'll take a look at this in a bit. However, I know other people are actively using Kapture/Discord right now so may want to the try the usual restart, etc.

**Comment by Endracion** [comment]
Uninstalling, reinstall without changing anything seems to have solved it haha, thanks.
