### ISSUE TITLE
Discord message doesn't respect events tab

### ISSUE THREAD

**Issue by kalilistic** [kalilistic/Dalamud.Kapture#29]
Report: When reflecting in Discord, it shows even the items I have used. Please tell me how to make it only show furnace items. By the way, "Use" is not checked in "Events" tab

**Comment by Endracion** [comment]
To add to this, I think that the filters applied don't apply to discord, it just sends everything?
Please correct me if I'm wrong, but now that the discord bridge started working for me, I only want to track my own items, but it's sending messages for other players.

**Comment by kalilistic** [comment]
Yeah, I think you are correct. Looks like the Event tab is only used at the moment for the overlay and is not checked for the discord feature which was not my intention.

**Comment by kalilistic** [comment]
Pushed an update with a fix.
