### ISSUE TITLE
_plugin.DataManager.path is not same as pluginconfig path

### ISSUE THREAD

**Issue by LittleNightmare** [kalilistic/Dalamud.Kapture#3]
_plugin.DataManager.path locate at default XIVLauncher pluginConfig, but my pluginConfig is not there. Same issue with pricecheck, Anna's plugins like Macroogy and DalamudPython (I guess others would have the same issue)

**Comment by kalilistic** [comment]
What is the path for your plugin config directory?

**Comment by LittleNightmare** [comment]
`F:\ffxiv\FFXIVQuickLauncher-CN\AppData\pluginConfigs`
![image](https://user-images.githubusercontent.com/19811879/112527428-ff925100-8ddd-11eb-9af9-d7f64f2182f4.png)

`C:\Users\XXXXX\AppData\Roaming\XIVLauncher\pluginConfigs`
![image](https://user-images.githubusercontent.com/19811879/112527255-d245a300-8ddd-11eb-9c9d-cc6c20e85de2.png)

**Comment by kalilistic** [comment]
Hey - what version of QuickLauncher are you using? Can share repo url?

**Comment by kalilistic** [comment]
Hi, I think this should be fixed. It's available now in my custom repo https://github.com/kalilistic/DalamudPluginRepo as well as the source code. If this works for you, I can push the same update to PriceCheck too.

**Comment by LittleNightmare** [comment]
WORK!
