### ISSUE TITLE
loot shows items but doesn't show who obtained, etc

### ISSUE THREAD

**Issue by jacob-keller** [kalilistic/Dalamud.Kapture#31]
I am having an issue with Kapture not seeming to record who obtained items, etc. I can see the data on items being added to the loot, and I can see the events like "obtained" but it doesn't show the player names.

I have the log window settings set to "Full Name" and I have the same config setting in the /lootconfig screen.

Any ideas what might be causing this?

**Comment by kalilistic** [comment]
Had someone else report this recently too so I need to take a look

**Comment by jacob-keller** [comment]
I did notice that I have the "show world name" option checked. Wonder if this impacts it?

**Comment by kalilistic** [comment]
Pushed an update with a fix.
