### ISSUE TITLE
Dice roll list - French

### ISSUE THREAD

**Issue by Karuyo** [kalilistic/Dalamud.Kapture#7]
Hello, the dice rolls list doesn't seems to work on my french version of the game.
The list is always empty. Using the test data in the settings works.
![List](https://user-images.githubusercontent.com/53560435/126870985-bd1286d2-a31e-4daf-8779-f4b504b89aab.png)

**Comment by kalilistic** [comment]
Thanks for the report. Going to get back to Kapture soon and will try to fix this.

**Comment by kalilistic** [comment]
Oh, total memory lapse. I never added support for FR - I should add a warning for unsupported languages. Something I might change one day...but Kapture uses chat logs to determine the loot messages. This was pretty easy to build but has the major downside that it's language-specific. I built support for English initially - and worked with others to add German and Chinese.

If you wanted to help add FR support - I have instructions here. Let me know if any questions. https://gist.github.com/kalilistic/7dbbbc3d21b320f195fe6503187f3db3
